# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfkUFmKTsXWdqTqYqGsAYXUKZJV4x_24
"""

pip install python-dotenv psycopg2

import pandas as pd
import plotly.graph_objects as go
from sqlalchemy import create_engine

# Connect database Supabase
db_url = (
    "postgresql://postgres.tchwwnlazebhayosesvf:ta28_monash"
    "@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres"
)
engine = create_engine(db_url)

# Extract data
query = "SELECT * FROM tree_cover_loss_aus ORDER BY year;"
df = pd.read_sql(query, engine)

# Create plot
fig = go.Figure()

fig.add_trace(go.Bar(
    x=df['year'],
    y=df['tree_cover_loss_ha'],
    name='Tree Cover Loss (ha)',
    marker_color='#07431E',
    yaxis='y1'
))

fig.add_trace(go.Scatter(
    x=df['year'],
    y=df['co2_emissions_mg'],
    name='CO₂ Emissions (Mg)',
    yaxis='y2',
    mode='lines+markers',
    marker_color='firebrick'
))

fig.update_layout(
    title='Tree Cover Loss & CO₂ Emissions in Victoria (2001–2023)',
    xaxis=dict(
        title='Year',
        showgrid=False
    ),
    yaxis=dict(
        title='Tree Cover Loss (ha)',
        side='left',
        showgrid=False
    ),
    yaxis2=dict(
        title='CO₂ Emissions (Mg)',
        overlaying='y',
        side='right',
        showgrid=False
    ),
    legend=dict(x=0.01, y=0.99),
    template='plotly_white',
    plot_bgcolor='white',
    paper_bgcolor='white',
    margin=dict(l=50, r=50, t=60, b=50),
    font=dict(
        family="Instrument Sans, sans-serif",
        size=14,
        color="black"
    )
)

fig.write_html("tree_cover_loss_plot.html")

import os
os.listdir('/content')

from google.colab import files
files.download("tree_cover_loss_plot.html")